# fly.toml app configuration file generated for dantutor on 2023-09-24T16:47:01+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dantutor"
primary_region = "jnb"

[build]
  image = "flyio/hellofly:latest"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
